name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conda_gcc_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_gcc_10.sh
  windows_vs2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
      - name: Build
        shell: pwsh
        run: |
          conda install -y cmake boost-cpp
          mkdir build
          cd build
          cmake ../ -G "Visual Studio 16 2019" -A x64 -DTANUKI_BUILD_TESTS=yes -DTANUKI_WITH_BOOST_S11N=yes
          cmake --build . --config Release
          ctest -j4 -V -C Release
